# Generated by Django 4.2.1 on 2023-07-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='to_do_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=50)),
                ('to_do_list', models.TextField(default='', verbose_name='Description')),
                ('completed', models.CharField(choices=[('Completed', 'Completed'), ('NotCompleted', 'Not Completed'), ('InProgress', 'In Progress')], default='c', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
